CHANGELOG.md

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/xmr-btc-swap/actions/runs/9745923622.
I've updated the changelog and bumped the versions in the manifest files in this commit: c15a5ec4cb947cb9f9c09793e4a316f59748e532.

Release version 0.13.1

---

CHANGELOG.md

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/xmr-btc-swap/actions/runs/9954181310.
I've updated the changelog and bumped the versions in the manifest files in this commit: c430e89502ae06e888d8482e21a0db11c437132d.

Release version 0.13.3

---

CHANGELOG.md

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/xmr-btc-swap/actions/runs/10102340827.
I've updated the changelog and bumped the versions in the manifest files in this commit: 8284bea778fb4003d339d6fc4ca93f6d8299e635.

Release version 0.13.4

---

README.md
swap/README.md

Since this is now a more general monorepo I moved the old README to swap/README.md and wrote a short, new one

docs: update READMEs

---

src-gui/package.json
src-gui/src/renderer/index.tsx
src-gui/src/renderer/store/storeRenderer.ts
src-gui/yarn.lock
swap/src/cli/api/tauri_bindings.rs

Closes https://github.com/UnstoppableSwap/xmr-btc-swap/issues/47

feat(gui): Preserve global state across page reloads

---

swap/src/cli/command.rs

The one by stackwallet is very slow. This one seems better.

feat(cli): Change default testnet electrum server

---

src-tauri/tauri.conf.json

feat(tauri): Automatically start frontend dev server

---

src-gui/src/renderer/api.ts
src-gui/src/renderer/components/modal/listSellers/ListSellersDialog.tsx
src-gui/src/renderer/components/modal/provider/ProviderInfo.tsx
src-gui/src/renderer/components/pages/swap/SwapWidget.tsx
src-gui/src/renderer/index.tsx
src-gui/src/renderer/rpc.ts
src-gui/src/store/features/providersSlice.ts
src-gui/src/utils/conversionUtils.ts
src-gui/src/utils/parseUtils.ts
src-tauri/src/lib.rs
swap/src/cli/api/request.rs
swap/src/cli/list_sellers.rs
swap/src/protocol/bob/swap.rs

Closes https://github.com/UnstoppableSwap/core/issues/46

 feat(gui): Allow discovery of sellers via connecting to rendezvous point 

---

Cargo.lock
src-gui/src/models/cliModel.ts
src-gui/src/renderer/components/modal/provider/ProviderListDialog.tsx
src-gui/src/renderer/components/pages/help/RpcControlBox.tsx
src-gui/src/renderer/components/pages/wallet/WithdrawWidget.tsx
src-gui/src/renderer/rpc.ts
src-gui/src/store/features/rpcSlice.ts
src-gui/src/store/hooks.ts
src-gui/src/utils/parseUtils.ts
src-tauri/src/lib.rs
swap/src/bin/asb.rs
swap/src/cli/api.rs
swap/src/cli/api/tauri_bindings.rs
swap/src/common/tracing_util.rs

This PR closes #18: we send logs from CLI to GUI and vice versa.

feat(cli+tauri): Send logs from host to guest

---

CHANGELOG.md
Cargo.lock
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11259165246.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0b3ce7766da6dfad6727a0009037c04cd36fc26c.

Release version 0.13.5

---

src-gui/src/renderer/components/pages/help/ExportDataBox.tsx
src-gui/src/renderer/components/pages/help/FeedbackInfoBox.tsx
src-gui/src/renderer/components/pages/help/HelpPage.tsx
src-gui/src/renderer/rpc.ts
src-tauri/src/lib.rs
swap/src/cli/api/request.rs

feat(tauri): allow data export

---

CHANGELOG.md
Cargo.lock
swap/Cargo.toml

Reverts UnstoppableSwap/core#107 due to https://github.com/UnstoppableSwap/core/issues/95

Revert "Release version 0.13.5"

---

src-gui/src/renderer/components/alert/DaemonStatusAlert.tsx
src-gui/src/renderer/components/modal/listSellers/ListSellersDialog.tsx
src-gui/src/renderer/rpc.ts
src-gui/src/store/middleware/storeListener.ts
src-gui/src/utils/sortUtils.ts

- **fix(gui): Signal to the user that we are checking status of remote node**
- **feat(gui): Connect to preset rendezvous nodes at startup**
- **feat(gui): Prioritize by price, prioritize asbs running latest version**

feat(gui): Connect to preset rendezvous nodes at startup

---

Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/lib.rs

- **feat(gui): Include version number in window title**
- **feat(gui): Kill monero-wallet-rpc if running in background**

feat(gui): Kill monero-wallet-rpc if running in background

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11847256201.
I've updated the changelog and bumped the versions in the manifest files in this commit: 4feaf8083a5e64d8cc6abd70f0fab58d617af768.

Release version 1.0.0-alpha.3

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11856778760.
I've updated the changelog and bumped the versions in the manifest files in this commit: 57c96d66236a1414e9185eba3bde263b76b28910.

Release version 1.0.0-rc.1

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11878360305.
I've updated the changelog and bumped the versions in the manifest files in this commit: 262b4a9b371012ff3e5925ff2ed40861144a2c8f.

Release version 1.0.0-rc.3

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11880246194.
I've updated the changelog and bumped the versions in the manifest files in this commit: 407e8b42bedbc374203c92f1152dc5bf86e1c84e.

Release version 1.0.0-rc.4

---

CHANGELOG.md
Cargo.lock
src-gui/src/renderer/components/alert/DaemonStatusAlert.tsx
src-gui/src/store/features/rpcSlice.ts
swap/src/cli/api.rs
swap/src/cli/api/tauri_bindings.rs
swap/src/monero/wallet_rpc.rs

CLI + GUI: At startup the wallets and tor client are started in parallel. This will speed up the startup time of the application.

feat(swap): Start wallets and tor client in parallel

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/12031970412.
I've updated the changelog and bumped the versions in the manifest files in this commit: aaece4896f4b3500d81f713fe3b256c7d48b6ad2.

Release version 1.0.0-rc.7

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/12164937634.
I've updated the changelog and bumped the versions in the manifest files in this commit: d22d89da5ce32eb47bf146471c75c6f0a7c41ac5.

Release version 1.0.0-rc.9

---

Cargo.lock
swap/Cargo.toml

Closes https://github.com/UnstoppableSwap/core/issues/231

bump: arti to 0.25.0

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/12458577763.
I've updated the changelog and bumped the versions in the manifest files in this commit: 4fd03175f952e1e576cc94dc66244c35465e896d.

Release version 1.0.0-rc.11

---

Cargo.lock
src-gui/src/renderer/background.ts
src-gui/src/renderer/components/modal/swap/pages/DebugPage.tsx
src-gui/src/renderer/components/modal/swap/pages/in_progress/ReceivedQuotePage.tsx
src-gui/src/store/features/rpcSlice.ts
src-gui/src/store/middleware/storeListener.ts
swap/Cargo.toml

- Fetch balance after swap is released
- Re-fetch database after progress event
- Change wording on progress page

fix(gui): Keep database/rpc state in sync

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/12777476735.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0bfb6bb37418bb1f6e19769d9b8274e7836e980e.

Release version 1.0.0-rc.12

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/12940807035.
I've updated the changelog and bumped the versions in the manifest files in this commit: 9dd7068da65f83e19f693401d16dc384cd3f6793.

Release version 1.0.0-rc.13

---

src-tauri/src/lib.rs

This should fix the ongoing static analysis issue on main branch and pull requests.

Run cargo fmt in src-tauri

---

dev_scripts/code2prompt_as_file_mac_os.sh
dev_scripts/code2prompt_to_clipboard.sh

**dev: Add code2prompt scripts to extract entire codebase into single file**

dev: Add code2prompt scripts to extract entire codebase into single file

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

Hi @Einliterflasche!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/14491913951.
I've updated the changelog and bumped the versions in the manifest files in this commit: 3fe7d15003975e7b46896b9769e9c6db23f0f09b.

Release version 1.0.0-rc.14

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/14526904933.
I've updated the changelog and bumped the versions in the manifest files in this commit: c892b1f8c44d0178aa92ceff2dda4c1fa49f3b77.

Release version 1.0.0-rc.17

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/14710980674.
I've updated the changelog and bumped the versions in the manifest files in this commit: 7a89ef9a8e6781019ee38f3d2e623bf76d49bfe4.

Release version 1.0.0-rc.19

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15099982194.
I've updated the changelog and bumped the versions in the manifest files in this commit: 41e5599aff0f0d3dc2a48337916064f676d49ac8.

Release version 1.1.0-rc.1

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15100545208.
I've updated the changelog and bumped the versions in the manifest files in this commit: 6274ad278ea7e172e4ff600c21253eda246edb78.

Release version 1.1.0-rc.2

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15101049958.
I've updated the changelog and bumped the versions in the manifest files in this commit: 1dd9074166e49c7c22897aad136849bda2a0eddd.

Release version 1.1.0-rc.3

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15112977129.
I've updated the changelog and bumped the versions in the manifest files in this commit: ccd5861896d315f98c0fd9df220b62d3ad2b6e0c.

Release version 1.1.0

---

dprint.json
justfile

This PR adds a justfile for easy and centralized command collection/execution.

feat(dev): add justfile

---

AGENT.md

- add `AGENT.md` with overview of key directories
- document which files change most in recent PRs
- outline how the components connect
- `git log --oneline -n 20 | head`
- `printf "%s" "$FILES" | tr ' ' '\n' | sort | uniq -c | sort -nr | head -n 6`

Add AGENT overview

---

AGENT.md

- document commit title style examples for PRs
- `git status --short`

docs: add PR title examples

---

swap/src/bitcoin/wallet.rs

- increase maximum relative Bitcoin lock transaction fee to 20%
- update unit tests for new fee ceiling

Update Bitcoin fee limit

---

src-gui/src/renderer/components/pages/help/ContactInfoBox.tsx

- point Feedback page GitHub link to the `UnstoppableSwap/core` repo
- `dprint --version` *(fails: command not found)*
- `cargo --version` *(fails: could not download file: No route to host)*

fix(gui): update feedback GitHub issue link

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15367696495.
I've updated the changelog and bumped the versions in the manifest files in this commit: cdda0054376848446129fa36e36eb17fe9e9e825.

Release version 1.1.3

---

src-gui/src/renderer/components/other/Units.tsx
src-gui/src/renderer/components/pages/help/SettingsBox.tsx

Reduce final `useAppSelector((s) => s.settings.X)` to `useSettings((s) => s.X)`

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15593739750.
I've updated the changelog and bumped the versions in the manifest files in this commit: 88377e2507add45e2203293436243851ca4f974c.

Release version 2.0.0-beta.2

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15608841312.
I've updated the changelog and bumped the versions in the manifest files in this commit: b497eef904799b10cac8105d76ebe753ba858824.

Release version 2.0.0

---

CHANGELOG.md
src-gui/src/renderer/components/modal/updater/UpdaterDialog.tsx
swap/src/bitcoin/electrum_balancer.rs

- **fix(wallet): Increase request_timeout to 7s, min_retries to 10 for Electrum load balancer**
- **fix(wallet): Backoff some time before trying Electrum request**

fix(wallet): Backoff for Electrum balancer

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15616454080.
I've updated the changelog and bumped the versions in the manifest files in this commit: 32bf5c9cae64d72ec81bb0ec3e865963bb8e270d.

Release version 2.0.2

---

CHANGELOG.md
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16347759155.
I've updated the changelog and bumped the versions in the manifest files in this commit: dedb2c0139c934ec6d10a10c39665ab77ffc4209.

Release version 2.4.3

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16350828279.
I've updated the changelog and bumped the versions in the manifest files in this commit: cb8390eecaa48b43d1975c88fd02b13681e282aa.

Release version 2.4.5

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16366453088.
I've updated the changelog and bumped the versions in the manifest files in this commit: 451545057e25cda798d4d70d281091818e9d4324.

Release version 2.5.6

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16555886695.
I've updated the changelog and bumped the versions in the manifest files in this commit: 47ffd14eda69efd920ef4cbf6a91e8707d8f6321.

Release version 3.0.0-beta.2

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16675980651.
I've updated the changelog and bumped the versions in the manifest files in this commit: f8d74efa5c35b822c73919eb89866c781a4c2b02.

Release version 3.0.0-beta.3

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16719778626.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0e8d6fa3e57cb67979e124e9036a17f04b1c4590.

Release version 3.0.0-beta.5

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/16841454598.
I've updated the changelog and bumped the versions in the manifest files in this commit: 5abb4f6b7c9117793184d5a6e2848403b663d7b1.

Release version 3.0.0-beta.7

---

CHANGELOG.md
Cargo.lock
monero-rpc-pool/Cargo.toml
monero-rpc-pool/src/bin/stress_test_downloader.rs
monero-rpc-pool/src/connection_pool.rs
monero-rpc-pool/src/main.rs
monero-rpc-pool/src/proxy.rs
swap/src/common/tor.rs

https://gitlab.torproject.org/tpo/core/arti/-/issues/2117

fix(monero-rpc-pool): TLS issues on macOS

---

CHANGELOG.md
Cargo.lock
monero-harness/src/lib.rs
monero-sys/Cargo.toml
monero-sys/src/lib.rs
swap-asb/src/main.rs
swap/Cargo.toml
swap/src/cli/api.rs
swap/src/monero/wallet.rs
swap/src/protocol/alice/state.rs
swap/src/protocol/bob/state.rs
swap/tests/harness/mod.rs

fix: Re-set restore height to chain tip after loading transaction

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/17222683554.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0ee0dd4c0726c3e94b2cc2d63679d30f6eb95fe6.

Release version 3.0.0-beta.12

---

.github/actions/set-monero-env/action.yml
.github/actions/setup-build-environment/action.yml
.github/workflows/build-gui-release-binaries.yml
.github/workflows/build-release-binaries.yml

Complete the work begun in #500.

CI: Complete CI configuration

---

README.md

Updated the release link in the README to point to the correct path.

Fix release link in README.md

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/17847026254.
I've updated the changelog and bumped the versions in the manifest files in this commit: 6b167c5d9e99920662ad26bd5a7a5c49b2ce2d60.

Release version 3.0.1

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/17890888551.
I've updated the changelog and bumped the versions in the manifest files in this commit: f93411bee45131786d555089e7ce1a9615201241.

Release version 3.0.2

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/17974812618.
I've updated the changelog and bumped the versions in the manifest files in this commit: c2fcc63c0c2ac28152f4f66cb991f73d5c1c3488.

Release version 3.0.3

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

Hi @Einliterflasche!
This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/18051491483.
I've updated the changelog and bumped the versions in the manifest files in this commit: 09796ca31ccd943568dc854146a20aecad4bfcf8.

Release version 3.0.4

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/18203805760.
I've updated the changelog and bumped the versions in the manifest files in this commit: 76cd73316e80b28f24620fe0888cb38254980e24.

Release version 3.0.6

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/18244785168.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0bf2ec1201cebfed2f364588036051230f3beaf3.

Release version 3.0.7

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/eigenwallet/core/actions/runs/18318468520.
I've updated the changelog and bumped the versions in the manifest files in this commit: a40a949026833a451ddff011a6fa3ac886ae61fa.

Release version 3.1.0
