eigenwallet/core

CHANGELOG.md
Cargo.lock
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/xmr-btc-swap/actions/runs/9807076769.
I've updated the changelog and bumped the versions in the manifest files in this commit: 095f9905d1469ff1ffebb32203d52a3bf9c883f0.

Release version 0.13.2

---

src-tauri/src/lib.rs
swap/src/cli/api.rs
swap/src/cli/command.rs

Move from a single creation function with 9 arguments to a builder style

refactor(cli): Builder pattern for constructing Context

---

.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml

Cross compilation is currently broken due to the missing system dependencies (libwebkit). This PR (temporarily) disabled that target.

chore(ci): Temporarily disable armv7 cross compilation 

---

Cargo.lock
monero-harness/Cargo.toml
monero-wallet/Cargo.toml
swap/sqlx-data.json
swap/src/cli/api.rs
swap/src/cli/api/request.rs
swap/src/database/sqlite.rs
swap/src/protocol.rs
swap/src/rpc/methods.rs
swap/tests/rpc.rs

- Use the Request trait introduced in https://github.com/UnstoppableSwap/xmr-btc-swap/pull/10 for the RPC server
- Delegate deserialization of RPC server method parameters to serde by using structs like BuyXmrArgs
- Remove `get_raw_states` RPC server method because it's not used
- Fix RPC server tests including removing test for the "log reference id" feature which was removed as part of https://github.com/UnstoppableSwap/xmr-btc-swap/pull/10
- Rename GetCurrentSwap struct to GetCurrentSwapArgs

refactor(cli): Refactor RPC server and fix tests

---

.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
src-tauri/Cargo.toml
src-tauri/src/lib.rs
swap/Cargo.toml
swap/src/cli/api.rs
swap/src/cli/api/tauri_bindings.rs

Introducing a feature flag in the `swap` crate that conditionally enables the `tauri` depencendy. This allows compiling the `swap` crate without the heavy `tauri` dependency. This also enables us to build arm binaries in the CI again.
This closes #32 and #34

feat(swap): tauri feature flag

---

Cargo.lock
src-gui/eslint.config.js
src-gui/package.json
src-gui/src/renderer/components/App.tsx
src-gui/src/renderer/components/icons/LinkIconButton.tsx
src-gui/src/renderer/components/pages/help/ContactInfoBox.tsx
src-gui/yarn.lock
src-tauri/Cargo.toml
src-tauri/capabilities/default.json
src-tauri/src/lib.rs

feat(gui): open links in default browser

---

.github/workflows/build-gui-preview-release-binaries.yml
src-gui/package.json
src-tauri/tauri.conf.json

- Adds a Github action file that build the binaries
- Run build command before tauri build is started
- disable tauri csp rules
- disable typescript compiler check before build

ci: create gui preview release on push to master

---

CHANGELOG.md
docs/cli/README.md
src-gui/src/renderer/components/modal/swap/pages/init/InitPage.tsx
src-gui/src/renderer/rpc.ts
swap/src/cli/api.rs
swap/src/cli/api/request.rs
swap/src/cli/command.rs
swap/src/rpc/methods.rs

This PR:
- allows --change-address to be omitted and default to internal wallet address (#1709). This is a change that is merged from upstream into our fork
- adds the necessary components for the tauri integration and the ui components to allow toggling between internal vs external refund address

feat(gui, swap): allow change-address to be omitted and default to internal wallet

---

swap/src/protocol/bob/swap.rs

Applies this PR to our fork:
https://github.com/comit-network/xmr-btc-swap/pull/1716

fix: Format cooperative redeem reject using thiserror (#1716)

---

swap/Cargo.toml

This is to fix the failing Dockerfile publish ci action

chore(swap): Disable cargo tauri integration feature by default

---

swap/src/monero/wallet_rpc.rs

The moneroworld node has been confirmed to have been operated by Chainalysis, a company specialising in blockchain surveillance. They are collecting the ip addresses of anyone who connects to the node.
https://www.digilol.net/blog/chainanalysis-malicious-xmr.html

fix(cli): Remove malicious node.moneroworld remote node

---

.github/workflows/ci.yml

We omit the `--all-features` for the tests run in the CI. There are no features in any of our crates besides `tauri` so this doesn't disable any features that might be required.

fix(ci): Disable Tauri feature for tests

---

Cargo.lock
src-gui/src/renderer/rpc.ts
src-tauri/Cargo.toml
swap/Cargo.toml
swap/src/cli/api/request.rs
swap/src/cli/api/tauri_bindings.rs
swap/src/cli/watcher.rs

Closes #43. This PR creates a new event, which is emitted by the watcher daemon when the BTC balance changes. Then, on the guest side, we simply update the balance when this event is received.

feat(tauri): send tauri event on btc balance change

---

src-gui/src/models/tauriModelExt.ts
src-gui/src/renderer/components/alert/UnfinishedSwapsAlert.tsx
src-gui/src/renderer/components/modal/feedback/FeedbackDialog.tsx
src-gui/src/renderer/components/modal/provider/ProviderInfo.tsx
src-gui/src/renderer/components/modal/swap/pages/SwapStatePage.tsx
src-gui/src/renderer/components/modal/swap/pages/done/BitcoinPunishedPage.tsx
src-gui/src/renderer/components/navigation/UnfinishedSwapsCountBadge.tsx
src-gui/src/renderer/components/pages/history/table/HistoryRowActions.tsx
src-gui/src/store/hooks.ts
src-gui/src/utils/conversionUtils.ts
src-gui/src/utils/multiAddrUtils.ts
src-gui/src/utils/sortUtils.ts

This PR applies all remaining changes from https://github.com/UnstoppableSwap/unstoppableswap-gui/pull/210
- Added checkbox option to attach daemon logs when submitting feedback
- Added "Outdated" chip with warning icon for providers running outdated asb versions
- Updated `BitcoinPunishedPage` to display different messages for BtcPunished and CooperativeRedeemRejected states (including reason for failed cooperative redeem)
- Added "Attempt recovery" button for swaps in BtcPunished state
- Modified `getBitcoinTxExplorerUrl` to use mempool.space instead of blockchair.com
- Added `useResumeableSwapsCountExcludingPunished` hook to count resumable swaps excluding punished ones, use it for the badge and alert
- Updated `sortProviderList` function to filter out incompatible providers before …

Merge changes from legacy GUI, allow daemon logs to be attached to feedback

---

Cargo.lock
src-gui/package.json
src-gui/yarn.lock
src-tauri/Cargo.toml
src-tauri/src/lib.rs

We use the [`single-instance`](https://v2.tauri.app/plugin/single-instance/) tauri plugin to enforce that only a single instance of the GUI is running concurrently.

feat(gui): Enforce single instance of GUI to be running

---

src-gui/src/renderer/components/alert/SwapStatusAlert.tsx

The manual cancel and refund button has been removed. This functionality is not currently implemented in the GUI, and the state machine will handle resuming the swap instead. This feature can be reimplemented later if needed.

fix(gui): Hide manual cancel and refund button

---

src-tauri/tauri.conf.json

This changed the "product name" of the GUI. This is the name that's displayed in the OS in a bunch of places.

feat(gui): Change product name to "UnstoppableSwap (new)"

---

CHANGELOG.md
swap/src/protocol/alice/swap.rs

There are a number of reasons the locking of the Monero funds could fail:
- Insufficient funds in wallet
- Network errors (`no connection to daemon`)
- Daemon not being fully synced
- `monero-wallet-rpc` crashed
We will retry continously until the cancel timelock expires.
Closes https://github.com/UnstoppableSwap/core/issues/138

feat(asb): Retry locking Monero

---

swap/src/asb/event_loop.rs

We accept cooperative redeem request in both `AliceState::BtcPunishable` and `AliceState::BtcPunished`. This allows Bob to request a cooperative redeem even if `tx_punish` has not been confirmed yet.

fix(asb): Accept cooperative redeem earlier

---

src-gui/src/renderer/components/modal/swap/SwapStateStepper.tsx
src-gui/src/renderer/components/modal/swap/pages/SwapStatePage.tsx
src-gui/src/renderer/components/modal/swap/pages/in_progress/StartedPage.tsx
src-gui/src/renderer/components/modal/swap/pages/in_progress/SwapSetupInflightPage.tsx
src-gui/src/renderer/components/modal/swap/pages/init/WaitingForBitcoinDepositPage.tsx
swap/src/cli/api/tauri_bindings.rs
swap/src/protocol/bob/swap.rs

We now display a `Starting swap with provider to lock ... BTC` page when the Bitcoin have been deposited and the swap setup is inflight.

feat(gui): Display state page for inflight swap setup

---

swap/src/monero/wallet_rpc.rs

Closes https://github.com/UnstoppableSwap/core/issues/152
I haven't been able to test this yet.

fix(gui, windows): Hide monero-wallet-rpc console window

---

CHANGELOG.md
Cargo.lock
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11840977054.
I've updated the changelog and bumped the versions in the manifest files in this commit: a3ff4c5b03d1c5ee9dd82227a1bde58ac7b6bee5.

Release version 1.0.0-alpha.1

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11843269671.
I've updated the changelog and bumped the versions in the manifest files in this commit: 29cbad0a7c4126ee056948f9f2ebd798f541904d.

Release version 1.0.0-alpha.2

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11869842886.
I've updated the changelog and bumped the versions in the manifest files in this commit: 5ea0623d3089be2a22bc2ba92740acf9421a84f4.

Release version 1.0.0-rc.2

---

CHANGELOG.md
Cargo.lock
swap/src/asb/event_loop.rs
swap/src/common/tracing_util.rs
swap/src/kraken.rs

Logs below DEBUG (network failures, balance warnings, ...) will be written to a log file that'll be deleted daily (24 log files, hourly rotated, deleted daily). All other logs will continue to be written to stdout/stderr and the permanent log file.

feat(swap): Log tracing in rolling log files

---

.github/workflows/build-gui-release-binaries.yml

Attempt at fixing https://github.com/UnstoppableSwap/core/issues/182. We are copying the system dependencies from https://github.com/gitbutlerapp/gitbutler/blob/master/.github/workflows/publish.yaml

fix(ci): Pin libwebkit2gtk to 2.44.0-2

---

CHANGELOG.md
Cargo.lock
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11917120299.
I've updated the changelog and bumped the versions in the manifest files in this commit: da57e08f27971c8294f1943a62890bbd20788b60.

Release version 1.0.0-rc.5

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/11951074618.
I've updated the changelog and bumped the versions in the manifest files in this commit: 0704d0e6630e8f1f846d220a0a3fc77a7a8803b2.

Release version 1.0.0-rc.6

---

src-tauri/tauri.conf.json
swap/src/bin/asb.rs
swap/src/bin/swap.rs
swap/src/cli/api.rs
swap/src/common/mod.rs

We check for updates in the background and warn if one is available. We do not check for updates on the cli

fix(asb): Check for updates in background

---

CHANGELOG.md
src-gui/yarn.lock
swap/src/asb/command.rs
swap/src/bin/asb.rs
swap/src/monero.rs
swap/src/protocol/alice/state.rs
swap/src/protocol/alice/swap.rs

Closes https://github.com/UnstoppableSwap/core/issues/211

feat(asb): Print more information when history command is invoked

---

src-gui/src/renderer/components/modal/swap/DepositAddressInfoBox.tsx
src-gui/src/renderer/components/modal/swap/pages/init/WaitingForBitcoinDepositPage.tsx

This PR adds a warning against replace-by-fee for deposit transactions.
Doing so will cause the app to fail to recognize the deposit. 
This leads to having to cancel the swap and start a new one.
The deposited funds can be used for that, there is no risk of loss of funds.

GUI: warn against replace-by-fee for deposit transactions

---

swap/src/cli/api.rs
swap/src/cli/command.rs
swap/src/monero/wallet_rpc.rs

There was an issue before we were falsely applying a default node to use and not actually iterating through our list and checking for availiability. This commit fixes this issue and removes a few dead nodes.

fix(cli): Correctly check for available nodes, remove dead nodes

---

.github/workflows/build-gui-release-binaries-cb.yml
.github/workflows/build-gui-release-binaries.yml

Occasionally our ci jobs would fail due to network errors. This is a known issue which is worked around by disabling http multiplexing, for now. Hopefully.

CI: fix spurious network erros

---

Cargo.lock

https://rustsec.org/advisories/RUSTSEC-2025-0006
https://rustsec.org/advisories/RUSTSEC-2024-0421
Also updated yanked crates `scc` and `sdd`.

deps: fix crate vulnerabilities

---

swap/src/monero/wallet.rs

Adds some verbose logging to identify the underlying issue of https://github.com/UnstoppableSwap/core/issues/274

fix(swap): Error handling for fallback during Monero tx monitoring

---

src-gui/src/renderer/components/navigation/NavigationFooter.tsx
swap/src/protocol/bob/swap.rs

When we can't find tx_cancel even though the cancel timelock expired, we publish it ourselves.
However, some users had a problem where the tx_cancel wasn't found even though it was already published.
This leads to the cli getting stuck in `CancelTimelockExpired` when it should go to `BtcCancelled`.
This commit introduces an additional log statement that will help us narrow down why that is.

cli: log the reason we can't find tx_cancel

---

CHANGELOG.md
Cargo.lock
swap/Cargo.toml
swap/src/asb/event_loop.rs

Quotes are now cached (Time-to-live of 2 minutes) to avoid overloading the maker with requests in times of high demand. We also upgraded the `arti-client` library to `0.29`.

feat(asb): Cache quotes for performance

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/14522249139.
I've updated the changelog and bumped the versions in the manifest files in this commit: 916d0e5cc3b4f7d37f585e1720391b58d4aa9246.

Release version 1.0.0-rc.16

---

src-gui/src/models/cliModel.ts
src-gui/src/renderer/components/modal/feedback/FeedbackDialog.tsx
src-gui/src/renderer/components/other/RenderedCliLog.tsx
src-gui/src/renderer/components/other/ScrollablePaperTextBox.tsx
src-gui/src/renderer/rpc.ts
src-gui/src/store/features/rpcSlice.ts
src-gui/src/utils/parseUtils.ts
src-tauri/src/lib.rs
swap/src/cli/api/request.rs

This PR allows users to edit the logs they can attach to feedabck messages, to check for things they don't want to send or redact them.  Closes #127.
This is how it currently looks:
https://github.com/user-attachments/assets/f40010e3-312f-4e65-889d-e6f33a8bb0f1

feat(gui): Review logs before sending feedback

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15028923894.
I've updated the changelog and bumped the versions in the manifest files in this commit: fcc5f16d92a96da7893e2513d55c53657d3af208.

Release version 1.0.0-rc.20

---

.github/workflows/ci.yml

The `ci.yml` currently accounts for 99% of our monthly used Github Action minutes. This restricts the `ci.yml` workflow to one concurrent run per git branch.
If you push to a branch and `ci.yml` is still pending from your previous commit, the old run will be cancelled and the new one will be ran.
See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs

feat(ci): Limit ci.yml to one concurrent running job per git branch

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15051592501.
I've updated the changelog and bumped the versions in the manifest files in this commit: 9d13ae0e27cb99f9232333cfa8ddc171bb5a6640.

Release version 1.0.0-rc.21

---

.github/workflows/build-release-binaries.yml
.github/workflows/ci.yml
.github/workflows/draft-new-release.yml
CHANGELOG.md
Cargo.lock
rust-toolchain.toml
src-gui/package.json
src-gui/src/renderer/components/modal/provider/MakerInfo.tsx
src-gui/src/utils/multiAddrUtils.ts
src-gui/src/utils/sortUtils.ts
src-gui/yarn.lock
src-tauri/Cargo.toml

- **bump(rust): Toolchain to 1.82**
- **bump(tauri): Bump some Tauri peer-dependencies**
- **fix(gui): Prefer maker with known version, bump MIN_ASB_VERSION to 1.1.0-rc.3**
- **amend: CHANGELOG.md**

fix: Issues with 1.1.0-rc

---

CHANGELOG.md
swap/src/bitcoin/wallet.rs

- prevent transient failures by adding retry logic to Bitcoin wallet sync
- note new behaviour in changelog
- `dprint check` *(fails: command not found)*
- `cargo clippy --workspace --locked --all-targets --all-features -- -D warnings` *(fails: could not download file due to network restrictions)*

fix(swap): Add retry logic for Bitcoin wallet sync

---

CHANGELOG.md
Cargo.lock
src-tauri/Cargo.toml
src-tauri/tauri.conf.json
swap/Cargo.toml

This PR was created in response to a manual trigger of the release workflow here: https://github.com/UnstoppableSwap/core/actions/runs/15138390105.
I've updated the changelog and bumped the versions in the manifest files in this commit: af28eef198d17c95dcc6ed37c6acbe158c62a7fa.

Release version 1.1.1

---

AGENT.md
CHANGELOG.md
dev-docs/asb/README.md
docs/pages/becoming_a_maker/overview.mdx

- document the `external_bitcoin_address` option in maker configuration in docs
- fix changelog entry wording
- `dprint check` *(fails: command not found)*
- `cargo clippy --workspace --tests --all-features -- -D warnings` *(fails: could not download Rust toolchain)*

Update docs for external bitcoin address

---

swap/src/monero.rs
swap/src/network/swap_setup/alice.rs

Attempt at fixing https://github.com/UnstoppableSwap/core/issues/370
Increased from 0.000016 XMR to 0.003 XMR

fix(monero): Conservative Monero fee for max giveable calcuation

---

CHANGELOG.md
Cargo.lock
monero-rpc-pool/Cargo.toml
monero-rpc-pool/src/bin/stress_test.rs
monero-rpc-pool/src/config.rs
monero-rpc-pool/src/connection_pool.rs
monero-rpc-pool/src/database.rs
monero-rpc-pool/src/lib.rs
monero-rpc-pool/src/main.rs
monero-rpc-pool/src/pool.rs
monero-rpc-pool/src/proxy.rs
monero-rpc-pool/src/types.rs
src-gui/src/renderer/components/pages/monero/components/WalletOverview.tsx
src-gui/src/renderer/components/pages/swap/swap/done/BitcoinRefundedPage.tsx
src-gui/src/renderer/rpc.ts
src-gui/src/store/features/walletSlice.ts
swap/src/bin/asb.rs
swap/src/cli/api.rs

- Responses are now streamed to the caller (after the first 1kb)
- TCP and Tor connections are cached
- "Time left till synced" improved

feat(monero-rpc-pool): TCP pool

---

swap-asb/Dockerfile
swap-controller/Dockerfile

See https://docs.docker.com/build/cache/optimize/#use-cache-mounts

 fix: mount apt cache as locked in docker buildkit
